---
- hosts: all
  become: true
  tasks:
    - name: "Anlegen des Benutzers"
      user:
        name: "{{ deploy_user }}"
        comment: "{{ deploy_user }}"-Benutzer
    - name: "Anlegen des .ssh-Ordners"
      file:
        path: /home/"{{ deploy_user }}"/.ssh
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: 0664
    - name: ""
    

