---
- hosts: all
  become: true
  tasks:
    - name: "Anlegen des Benutzers"
      user:
        name: "{{ deploy_user }}"
        comment: "{{ deploy_user }}"
    - name: "Anlegen des .ssh-Ordners"
      file:
        path: /home/"{{ deploy_user }}"/.ssh
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: 0664
    - name: "Anlegen der authorized_key Datei"
      authorized_key:
        user: "{{ deploy_user }}"
        state: present
        key: "{{ lookup{'file', '/home/<< Hier NAME EINSETZEN !!!!>>/.ssh/id_rsa.pub'} }}"
    - name: "ANpassen der AllowUsers in der /etc/ssh/sshd_config"
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^AllowUsers'
        line: 'monitoring@192.168.1.20'
    - name: "Neustarten des SSH-Daemons"
      service:
        name: sshd
        state: restarted

